# Generated by Django 5.1.2 on 2024-11-12 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PPN_PPnBM', 'PPN dan PPnBM'), ('PPH_B', 'PPh Badan'), ('PPH_P', 'PPh Pemotongan/Pemungutan'), ('PPH_OP', 'PPh Orang Pribadi'), ('E_SPT', 'E-Spt'), ('PPH_21', 'PPh Pasal 21/26'), ('TA', 'Tax Amnesty'), ('AKP', 'Akuntansi Pajak'), ('PINT', 'Perpajakan Internasional'), ('BERITA', 'Bahas Berita'), ('PDRD', 'Pajak Daerah dan Retribusi Daerah'), ('PBB', 'Pajak Bumi dan Bangunan')], max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussions.discussion')),
            ],
        ),
    ]
