# Generated by Django 5.1.4 on 2025-05-03 09:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artikel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikel',
            name='image',
            field=models.ImageField(default='', upload_to='artikel/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikel',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published At'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated At'),
        ),
    ]
