# Generated by Django 5.1.4 on 2025-05-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_artikel_author_artikel_created_at_artikel_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='status',
        ),
        migrations.AddField(
            model_name='artikel',
            name='draft_for',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Draft For'),
        ),
    ]
