# Generated by Django 5.1.4 on 2025-05-31 10:16

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_alter_artikel_author_alter_artikel_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='author',
        ),
        migrations.AddField(
            model_name='artikel',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='artikel_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='artikel_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waktu Buat'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Hapus'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='description',
            field=models.TextField(verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='image',
            field=models.ImageField(upload_to='artikel/', verbose_name='Gambar'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Publish'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Update'),
        ),
        migrations.CreateModel(
            name='ContentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(help_text='Path to the file in S3 storage', max_length=255, verbose_name='File Path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Buat')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Hapus')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_media', to='artikel.artikel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_media_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
