# Generated by Django 5.1.4 on 2025-05-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0005_remove_artikel_author_artikel_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Judul'),
        ),
    ]
